import {
  Sparkles,
  Code,
  FileText,
  Image,
  Music,
  Calculator,
  Languages,
  PenTool,
  Briefcase,
  MessageSquare,
  BookOpen,
  Bot,
  Brain,
  Cpu,
  Database,
  Globe,
  Heart,
  Home,
  Key,
  Lightbulb,
  Mail,
  Map,
  Mic,
  Newspaper,
  Palette,
  Phone,
  PieChart,
  Plane,
  Rocket,
  Scan,
  Search,
  Shield,
  Star,
  Sun,
  Target,
  Terminal,
  Wrench,
  Umbrella,
  User,
  Video,
  Watch,
  Wifi,
  Wind,
  Zap,
  Camera,
  Clock,
  Cloud,
  Coffee,
  Compass,
  Activity,
  AlarmClock,
  Anchor,
  Award,
  BarChart3,
  Bell,
  Bookmark,
  Box,
  Building,
  Calendar,
  Car,
  Cat,
  CheckCircle,
  Clipboard,
  Crown,
  Diamond,
  Droplet,
  Ear,
  Eye,
  Feather,
  Flag,
  Flower,
  Flower2,
  Gift,
  Glasses,
  Hand,
  Headphones,
  Hourglass,
  IceCream,
  Leaf,
  Link,
  Lock,
  Megaphone,
  Moon,
  Mountain,
  Mouse,
  Navigation,
  Network,
  Package,
  Paintbrush,
  Paperclip,
  Pen,
  Pencil,
  Pin,
  Puzzle,
  Quote,
  Radar,
  RefreshCcw,
  Send,
  Settings,
  Snowflake,
} from 'lucide-react'

export const iconComponents = [
  Sparkles, Code, FileText, Image, Music, Calculator, Languages, PenTool,
  Briefcase, MessageSquare, BookOpen, Bot, Brain, Cpu, Database, Globe,
  Heart, Home, Key, Lightbulb, Mail, Map, Mic, Newspaper, Palette, Phone,
  PieChart, Plane, Rocket, Scan, Search, Shield, Star, Sun, Target, Terminal,
  Wrench, Umbrella, User, Video, Watch, Wifi, Wind, Zap, Camera, Clock, Cloud,
  Coffee, Compass,
  Activity, AlarmClock, Anchor, Award, BarChart3, Bell, Bookmark, Box,
  Building, Calendar, Car, Cat, CheckCircle, Clipboard, Crown, Diamond,
  Droplet, Ear, Eye, Feather, Flag, Flower, Flower2, Gift, Glasses,
  Hand, Headphones, Hourglass, IceCream, Leaf, Link, Lock, Megaphone,
  Moon, Mountain, Mouse, Navigation, Network, Package, Paintbrush, Paperclip,
  Pen, Pencil, Pin, Puzzle, Quote, Radar, RefreshCcw, Send, Settings, Snowflake,
]

export const iconNames = [
  'Sparkles', 'Code', 'FileText', 'Image', 'Music', 'Calculator', 'Languages', 'PenTool',
  'Briefcase', 'MessageSquare', 'BookOpen', 'Bot', 'Brain', 'Cpu', 'Database', 'Globe',
  'Heart', 'Home', 'Key', 'Lightbulb', 'Mail', 'Map', 'Mic', 'Newspaper', 'Palette', 'Phone',
  'PieChart', 'Plane', 'Rocket', 'Scan', 'Search', 'Shield', 'Star', 'Sun', 'Target', 'Terminal',
  'Wrench', 'Umbrella', 'User', 'Video', 'Watch', 'Wifi', 'Wind', 'Zap', 'Camera', 'Clock', 'Cloud',
  'Coffee', 'Compass',
  'Activity', 'AlarmClock', 'Anchor', 'Award', 'BarChart3', 'Bell', 'Bookmark', 'Box',
  'Building', 'Calendar', 'Car', 'Cat', 'CheckCircle', 'Clipboard', 'Crown', 'Diamond',
  'Droplet', 'Ear', 'Eye', 'Feather', 'Flag', 'Flower', 'Flower2', 'Gift', 'Glasses',
  'Hand', 'Headphones', 'Hourglass', 'IceCream', 'Leaf', 'Link', 'Lock', 'Megaphone',
  'Moon', 'Mountain', 'Mouse', 'Navigation', 'Network', 'Package', 'Paintbrush', 'Paperclip',
  'Pen', 'Pencil', 'Pin', 'Puzzle', 'Quote', 'Radar', 'RefreshCcw', 'Send', 'Settings', 'Snowflake',
]

export const colors = [
  'from-violet-500 to-purple-500',
  'from-blue-500 to-cyan-500',
  'from-green-500 to-emerald-500',
  'from-pink-500 to-rose-500',
  'from-orange-500 to-red-500',
  'from-cyan-500 to-teal-500',
  'from-indigo-500 to-blue-500',
  'from-rose-500 to-pink-500',
  'from-amber-500 to-orange-500',
  'from-teal-500 to-green-500',
  'from-purple-500 to-fuchsia-500',
  'from-red-500 to-orange-500',
  'from-yellow-400 to-orange-500',
  'from-emerald-500 to-teal-500',
  'from-sky-500 to-blue-500',
  'from-fuchsia-500 to-purple-500',
  'from-lime-500 to-green-500',
  'from-purple-500 to-indigo-500',
  'from-blue-400 to-indigo-500',
  'from-pink-400 to-purple-500',
  'from-cyan-400 to-blue-500',
  'from-orange-400 to-pink-500',
  'from-green-400 to-cyan-500',
  'from-rose-400 to-red-500',
  'from-teal-400 to-emerald-500',
  'from-amber-400 to-yellow-500',
]

export function getIconComponent(iconName: string | null, size: 'sm' | 'md' | 'lg' | 'xl' = 'md'): React.ReactNode {
  const sizeClasses = {
    sm: 'size-4',
    md: 'size-5',
    lg: 'size-6',
    xl: 'size-10',
  }

  if (!iconName) return <Bot className={sizeClasses[size]} />
  // 支持数字索引（群聊存储的是索引字符串）
  const index = /^\d+$/.test(iconName) ? parseInt(iconName, 10) : iconNames.indexOf(iconName)
  if (index === -1 || index >= iconComponents.length) return <Bot className={sizeClasses[size]} />
  const IconComponent = iconComponents[index]
  return <IconComponent className={sizeClasses[size]} />
}